/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evm.Gui;

import evm.admin;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author robinhood
 */
public class admin_space extends javax.swing.JFrame {

    /**
     * Creates new form admin_space
     */
    public admin_space() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        result = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        n1 = new javax.swing.JLabel();
        v1 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrator");

        result.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        result.setText("Results");
        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Headboy");

        n1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n1.setText("*****");

        v1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        v1.setText("*****");

        reset.setText("Reset Database");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Votes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(84, 84, 84)
                                    .addComponent(reset))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(jLabel1)
                                    .addGap(39, 39, 39)
                                    .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(52, 52, 52)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(logout)
                                .addComponent(v1)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(result))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result)
                .addGap(20, 20, 20)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(v1)
                    .addComponent(n1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset)
                    .addComponent(logout))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
  try{    Class.forName("com.mysql.jdbc.Driver");
        Connection cn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/evm","root","");
        Statement st=cn.createStatement();
        ResultSet rs1;
        String q1;
        System.out.println("okay1");
        q1="select name,vote  from headboy where vote in(select max(vote) from headboy);";
        rs1=st.executeQuery(q1);
        rs1.next();
        n1.setText(rs1.getString(1));
        v1.setText(""+rs1.getInt(2));
                
        
       /* rs1=st.executeQuery(q2);
        rs2.next();
        rs3=st.executeQuery(q3);
        rs3.next();
        rs4=st.executeQuery(q4);
        rs4.next();
        System.out.println("okay3");
        //n1.setText(rs1.getString(1));
        System.out.println("okay4");
        int p=rs1.getInt(2);
        System.out.println(""+p);
       // System.out.println(rs1.getInt(0));
        v1.setText(""+rs1.getInt(2));
        System.out.println("ok5");
       // n2.setText(rs2.getString(1));
        v2.setText(""+rs2.getInt(2));
       // n3.setText(rs3.getString(1));
        v3.setText(""+rs3.getInt(2));
        //n4.setText(rs4.getString(1));
        v4.setText(""+rs4.getInt(2));*/
        cn.close();
        st.close();
        
        
        
  }catch(Exception e){
      System.out.println(""+e);
  }
    }//GEN-LAST:event_resultActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection cn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/evm","root","1234");
        Statement st=cn.createStatement();
       String q1,q2,q3;
       q1="UPDATE headboy SET vote=0;";
       st.executeUpdate(q1);
       
       q2="drop table if exists logged;";
       st.executeUpdate(q2);
       q3="create table logged(reg int(8));";
       st.executeUpdate(q3);
       cn.close();
       st.close();
}
catch(Exception e){
   // System.out.println(""+e);
}
    }//GEN-LAST:event_resetActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        admin log=new admin();
        log.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_space.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_space.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_space.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_space.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_space().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JButton logout;
    private javax.swing.JLabel n1;
    private javax.swing.JButton reset;
    private javax.swing.JButton result;
    private javax.swing.JLabel v1;
    // End of variables declaration//GEN-END:variables
}
