/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evm;

/**
 *9495460399
 * @author robinhood
 */
public class Trial extends javax.swing.JFrame {

    /**
     * Creates new form Trial
     */
    public Trial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nota = new javax.swing.JButton();
        cand6 = new javax.swing.JButton();
        cand1 = new javax.swing.JButton();
        cand8 = new javax.swing.JButton();
        cand9 = new javax.swing.JButton();
        cand5 = new javax.swing.JButton();
        cand4 = new javax.swing.JButton();
        cand3 = new javax.swing.JButton();
        cand2 = new javax.swing.JButton();
        cand7 = new javax.swing.JButton();
        cand10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nota.setText("NOTA");
        nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notaActionPerformed(evt);
            }
        });

        cand6.setText("cand 6");
        cand6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cand6ActionPerformed(evt);
            }
        });

        cand1.setText("cand 1");
        cand1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cand1ActionPerformed(evt);
            }
        });

        cand8.setText("cand 8");
        cand8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cand8ActionPerformed(evt);
            }
        });

        cand9.setText("cand 9");
        cand9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cand9ActionPerformed(evt);
            }
        });

        cand5.setText("cand 5");
        cand5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cand5ActionPerformed(evt);
            }
        });

        cand4.setText("cand 4");
        cand4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cand4ActionPerformed(evt);
            }
        });

        cand3.setText("cand 3");
        cand3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cand3ActionPerformed(evt);
            }
        });

        cand2.setText("cand 2");
        cand2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cand2ActionPerformed(evt);
            }
        });

        cand7.setText("cand 7");
        cand7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cand7ActionPerformed(evt);
            }
        });

        cand10.setText("cand 10");
        cand10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cand10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cand5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cand2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cand1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cand3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cand4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(nota, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cand7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cand6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cand8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cand9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cand10, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(cand1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(cand2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cand3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cand4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cand5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(cand6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cand7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cand8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cand9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nota, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cand10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notaActionPerformed

    private void cand6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cand6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cand6ActionPerformed

    private void cand1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cand1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cand1ActionPerformed

    private void cand8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cand8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cand8ActionPerformed

    private void cand9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cand9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cand9ActionPerformed

    private void cand5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cand5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cand5ActionPerformed

    private void cand4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cand4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cand4ActionPerformed

    private void cand3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cand3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cand3ActionPerformed

    private void cand2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cand2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cand2ActionPerformed

    private void cand7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cand7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cand7ActionPerformed

    private void cand10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cand10ActionPerformed
        
    }//GEN-LAST:event_cand10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cand1;
    private javax.swing.JButton cand10;
    private javax.swing.JButton cand2;
    private javax.swing.JButton cand3;
    private javax.swing.JButton cand4;
    private javax.swing.JButton cand5;
    private javax.swing.JButton cand6;
    private javax.swing.JButton cand7;
    private javax.swing.JButton cand8;
    private javax.swing.JButton cand9;
    private javax.swing.JButton nota;
    // End of variables declaration//GEN-END:variables
}
